app:
  twitter:
    consumer-key: consumer-key
    consumer-secret: consumer-secret
    access-token: access-token
    access-token-secret: access-token-secret
    tweets-per-search: 10

server:
  port: 8084
